baseurl: "https://example.com"
languageCode: "en-us"
title: "Tommy's blog"
theme: "hugo-tania"
paginate: 10

disqusShortname: xuyunan

params:
  enableFootnotes: true
  author: "xuyunan"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    email: xu_yunan@163.com
    github: https://github.com/xuyunan
    twitter: https://twitter.com/xuyunan
  
  # Comments settings
  comments:
    enabled: true
    provider: giscus

    giscus:
      repo: xuyunan/xuyunan.github.io
      id: R_kgDOHDKDYg
      category:
        name: Announcements
        id: DIC_kwDOHDKDYs4COQxq

  markup:
    highlight:
      noClasses: false
      lineNos: true
    goldmark:
      renderer:
        unsafe: true

  outputs:
    home: ["HTML", "RSS", "JSON"]