baseURL = "https://xuyunan.github.io"
languageCode = "zh-CN"
title = "Tommy's blog"
disableKinds = ["section", "categories", "tags"]
pygmentsCodeFences = false
pygmentsUseClasses = false
paginate = 9999
minify = true
disableHugoGeneratorInject = true

theme = "hugo-fengcheng"

[taxonomies]
  tag = "tags"
  category = "categories"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[Author]
  name = "xuyunan"

[params]
  description = "烂笔头日记"
  author = "xuyunan"
  copyright = "xuyunan"
  logo = "/assets/favicon.png"

  # Comments settings
  [params.comments]
    enabled = true
    provider = "giscus"

    [params.comments.giscus]
        repo = "xuyunan/xuyunan.github.io"
        id = "R_kgDOHDKDYg"
        [params.comments.giscus.category]
          name = "Announcements"
          id = "DIC_kwDOHDKDYs4COQxq"

[frontmatter]
  date  = [":filename", ":default"]
  author = ""
  github = ""
  facebook = ""
  og_image = ""
  sitename = "Liste"
  twitter = ""

[permalinks]
  # posts = "/:year/:month/:day/:filename"
  posts = "/:filename"
  pages = "/:slug"
  photos = "/:year/:month/:day/:filename"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "index"
    name       = "Index"
    url        = "/"
    weight     = -111

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects/"
    weight     = -30

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = -20
    

# [markup]
#   [markup.highlight]
#     anchorLineNos = false
#     codeFences = true
#     guessSyntax = true
#     hl_Lines = ""
#     lineAnchors = ""
#     lineNoStart =1
#     lineNos = true
#     lineNumbersInTable = true
#     noClasses = true
#     style = "monokai"
#     tabWidth = 4
